namespace IID.Application.Vehicles.Queries.Dtos;

public sealed record VehicleResponse(
    Guid Id,
    string Vin,
    string StockNumber,
    string Make,
    string Model,
    int Year,
    string Color,
    int Mileage,
    string FuelType,
    decimal PurchasePriceAmount,
    string PurchasePriceCurrency,
    decimal AskingPriceAmount,
    string AskingPriceCurrency,
    decimal? SoldPriceAmount,
    string? SoldPriceCurrency,
    DateTimeOffset? SoldAtUtc,
    decimal? GrossProfitAmount,
    decimal? GrossMarginPercent,
    string Status,
    DateTimeOffset DateAddedToInventoryUtc,
    int DaysInInventory,
    bool IsAging,
    string AgingSeverity,
    string DemandLevel,
    int DemandScore,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    string RowVersion,
    Guid? DealershipId = null,
    string? DealershipName = null)
{
    public static VehicleResponse From(Vehicle v, VehicleAnalyticsService analytics)
        => new(
            v.Id,
            v.Vin.Value,
            v.StockNumber ?? string.Empty,
            v.Make,
            v.Model,
            v.Year,
            v.Color,
            v.Mileage,
            v.FuelType.ToString(),
            v.PurchasePrice.Amount,
            v.PurchasePrice.Currency,
            v.AskingPrice.Amount,
            v.AskingPrice.Currency,
            v.SoldPrice?.Amount,
            v.SoldPrice?.Currency,
            v.SoldAt,
            v.GrossProfit?.Amount,
            v.GrossMarginPercent,
            v.Status.ToString(),
            v.DateAddedToInventory,
            analytics.DaysInInventory(v),
            analytics.IsAging(v),
            analytics.GetAgingSeverity(v).ToString(),
            analytics.GetDemandLevel(v).ToString(),
            analytics.GetDemandScore(v),
            v.CreatedAt,
            v.UpdatedAt,
            // Base64-encode the SQL Server rowversion so clients can echo it back
            // for optimistic concurrency on subsequent updates.
            Convert.ToBase64String(v.RowVersion),
            v.DealershipId != Guid.Empty ? v.DealershipId : null,
            v.Dealership?.Name);
}
